@Library("jenkins-shared-library@newJFversion")_

env.MAVEN_CENTRAL="${MAVEN_CENTRAL_COMMON}"
env.MAPR_CENTRAL="${MAPR_CENTRAL_COMMON}"
env.MAPR_RELEASES_REPO="${MAPR_RELEASES_REPO_COMMON}"
env.MAPR_SNAPSHOTS_REPO="${MAPR_SNAPSHOTS_REPO_COMMON}"
env.MAPR_MAVEN_REPO="${MAPR_SNAPSHOTS_REPO_COMMON}"

ARTIFACTORY_SERVER=''
YAML_CONFIG=''
env.REPOSITORY_NAME=''
env.GIT_REPO_URL=''
env.GIT_SHORT_COMMIT_SHA=''
env.CURRENT_BUILD_TAG=''
env.BUILD_BY_TAG=false

env.ARTIFACTORY_PATH=''
env.ID=''
env.MAKEFILE_ARGS=''
env.PROJECT=''

pipeline {
  agent none
  triggers {
    pollSCM 'H/5 * * * *'
  }
  options {
    skipDefaultCheckout()
    disableConcurrentBuilds()
    timestamps()
  }
  parameters {
    choice(name: 'BUILD_TYPE', choices: ['Dev','EBF','Release'], description: 'default - Dev. EBF and Release args you can use only in release branches')
    string(name: 'MAKEFILE_ENV_VARS', defaultValue: '', description: 'Variables you can pass to makefile (command will be: make {THIS VAR} {project-name}). Please DO NOT put component_branch_name')
  }
  stages {
    stage("Setup settings and variables") {
      agent {label "redhat8"}
      steps {
        script {
          ARTIFACTORY_SERVER = Artifactory.server 'artifactory.devops.lab'
          YAML_CONFIG = initVariablesWithYAMLConfig()
        }
      }
    }

    stage("Build & Sign & Upload to Artifactory") {
      agent none
      steps {
        script {
          buildInParallel=[:]
          YAML_CONFIG.build.each {
            buildInParallel["Build ${it.name}"] = { ->

              node (it.hostmachine_jenkins_label) {
                checkout scm
                build(it)
                if(it.rpmSign == true)
                  signing.rpmSign("dist")
                getVersionAndUploadToArtifactory()
              }

            }
          }
          parallel buildInParallel
        }
      }
    }

    stage ("Whitesource Scan") {
      agent {label "redhat8"}
      when {
        equals (actual: YAML_CONFIG.whitesourceScan, expected: true)
      }
      steps {
        script {
          checkout scm
          ws.dockerScan()
        /*Get token of product. We have to communicate with WS API only using 64-digits project's token.
          We are sending request to API and get ALL "project+token" pairs. Then parse this information and find token for current project*/
          productToken = ws.getWSProductToken()

          //Get reports (Excel and json) from WS site and save these reports to files. Once for each format
          ws.getWSReports(productToken)

          //Move latest reports to the "old" folder in Artifactory
          ws.moveOldWsReports(ARTIFACTORY_SERVER)

          //Upload reports (Excel and json) to the Artifactory (to the latest folder)
          ws.uploadToArtifactory(ARTIFACTORY_SERVER)
        }
      }
    }

  }
  post {
    failure {
      script {
        postActions.failure()
      }
    }
    fixed {
      script {
        postActions.fixed()
      }
    }
    aborted {
      script {
        postActions.aborted()
      }
    }
    success {
      script {
        postActions.success()
      }
    }
    always {
      script {
        postActions.always()
      }
    }
  }
}

def build(yamlCurrentBuildItem) {
  def image = yamlCurrentBuildItem.image.replace("_defaultregistry_", DOCKER_REGISTRY)
  def buildCommand = yamlCurrentBuildItem.basicBuildCommands.replace("_MAKEFILE_ARGS_","TIMESTAMP=${ID} ${MAKEFILE_ARGS}")

  configFileProvider([configFile(fileId: 'maven_settings', variable: 'mvn_settings')]) {
    sh "cat ${env.mvn_settings} > settings.xml"
  }
  docker.image(image).inside (
  "-e MAPR_MIRROR=${MAPR_MIRROR} \
  -e MAPR_CENTRAL=${MAPR_CENTRAL} \
  -e MAVEN_CENTRAL=${MAVEN_CENTRAL} \
  -e MAPR_MAVEN_REPO=${MAPR_MAVEN_REPO} \
  -e BUILD_NUMBER=${ID}.${BUILD_NUMBER} \
  -e MAPR_RELEASES_REPO=${MAPR_RELEASES_REPO} \
  -e MAPR_SNAPSHOTS_REPO=${MAPR_SNAPSHOTS_REPO} \
  -v /root/.m2:/root/.m2:rw \
  -v /root/yum-proxy.conf:/etc/yum.conf:ro \
  -v /etc/hosts:/etc/hosts:ro \
  -v /root/apt-proxy.conf:/etc/apt/apt.conf.d/proxy.conf:ro \
  -v /root/.gradle/gradle.properties:/root/.gradle/gradle.properties:ro \
  -v /etc/profile.d/proxy.sh:/etc/profile.d/proxy.sh:ro \
  -e ANT_OPTS=\"-Dhttp.proxyHost=${HPE_PROXY_HOST} -Dhttp.proxyPort=${HPE_PROXY_PORT} -Dhttps.proxyHost=${HPE_PROXY_HOST} -Dhttps.proxyPort=${HPE_PROXY_PORT} -Dhttp.nonProxyHosts='${HPE_PROXY_EXCEPTIONS}'\" \
  -e MAVEN_OPTS=\"-Dhttp.proxyHost=${HPE_PROXY_HOST} -Dhttp.proxyPort=${HPE_PROXY_PORT} -Dhttps.proxyHost=${HPE_PROXY_HOST} -Dhttps.proxyPort=${HPE_PROXY_PORT} -Dhttp.nonProxyHosts='${HPE_PROXY_EXCEPTIONS}'\" \
  -v /etc/localtime:/etc/localtime:ro \
  -v /root/.ssh:/root/.ssh:rw \
  -v ${WORKSPACE}/settings.xml:/root/.m2/settings.xml:ro") {
    sh """
      cat /etc/*-release > os_release_version.txt; \
      ${buildCommand}
    """
  }
}

def getVersionAndUploadToArtifactory() {
  def osVersionContainerRaw = sh script: 'cat os_release_version.txt', returnStdout:true
  artifactory.uploadToArtifactoryWithOSVersions(ARTIFACTORY_SERVER, osVersionContainerRaw)
}
