#!/bin/bash

[ -n "$VERBOSE" ] && echo "postrm called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x


after_remove() {
    rm -f "__PREFIX__/roles/nifi"
}

after_purge() {
    rm -Rf "__PREFIX__/nifi/"
}

#
# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
#
case "$1" in
    upgrade)
        ;;
    purge)
        after_remove
        after_purge
        ;;
    remove|disappear)
        after_remove
        ;;

    abort-install|abort-upgrade|failed-upgrade)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac