#!/bin/bash

[ -n "$VERBOSE" ] && echo "preinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x

#
# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#

copy_old_data() {
    local MY_OLD_HOME_DIR="${1}"
    local MY_OLD_TIMESTAMP_VERSION="${2}"

    mkdir -p __PREFIX__/nifi/nifi-$MY_OLD_TIMESTAMP_VERSION
    cp -r $MY_OLD_HOME_DIR/* __PREFIX__/nifi/nifi-${MY_OLD_TIMESTAMP_VERSION}
}

case "$1" in
    install)
        ;;

    upgrade)
      if [ -n "$2" ]; then
        MY_OLD_TIMESTAMP_VERSION=$2
        MY_OLD_3DIGIT_VERSION="$( echo $MY_OLD_TIMESTAMP_VERSION| cut -d'.' -f1-3 )"
        MY_OLD_HOME_DIR=__PREFIX__/nifi/nifi-$MY_OLD_3DIGIT_VERSION

        rm -rf "${MY_OLD_HOME_DIR}/work"
        copy_old_data "${MY_OLD_HOME_DIR}" "${MY_OLD_TIMESTAMP_VERSION}"
        rm -rf "${MY_OLD_HOME_DIR}/lib/*"
      fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac