#!/bin/bash

[ -n "$VERBOSE" ] && echo "preinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x

#
# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#

copy_old_data() {
    MY_OLD_TIMESTAMP=$1
    MY_OLD_CD_VERSION="$( echo $MY_OLD_TIMESTAMP| cut -d'.' -f1-3 )"
    MY_OLD_CD_HOME=__PREFIX__/nifi/nifi-$MY_OLD_CD_VERSION
    mkdir -p __PREFIX__/nifi/nifi-$MY_OLD_TIMESTAMP
    cp -r $MY_OLD_CD_HOME/* __PREFIX__/nifi/nifi-${MY_OLD_TIMESTAMP}
}

case "$1" in
    install)
        ;;

    upgrade)
      if [ -n "$2" ]; then
        copy_old_data "$2"
      fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac